url: http://blog.zoujinglin.com.cn
# url: http://0.0.0.0:4000

# Dependencies
highlighter:      rouge
markdown:         kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge


# Permalinks
permalink:        pretty

# site
title:            JanZou
tagline:          'programmer, analyst'
description:      'Hello, I am JanZou.'

paginate:         8
paginate_path: 'page:num'

future:      false
show_drafts: nil
limit_posts: 0

gems: [jekyll-paginate]







