url: http://blog.zoujinglin.com.cn
# url: http://0.0.0.0:4000

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# site
title:            JanZou
tagline:          'programmer'
description:      'Hello, I am JanZou.'

paginate:         5
paginate_path: 'page:num'

future:      false
show_drafts: nil
limit_posts: 0







